## Import Libraries

In [2]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from sqlalchemy import create_engine

### Test for Response Status

In [4]:
url = 'https://www.jumia.com.ng/'
r = requests.get(url)
print(r.status_code)

200

In [6]:
# https://www.neostore.ng/
url1 = 'https://www.neostore.ng/'
r1 = requests.get(url)
print(r1)

<Response [200]>

In [7]:
print(r.text)

<!DOCTYPE html><html lang="en" dir="ltr"><head><meta charset="utf-8"/><title>Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport</title><meta property="og:image" content="https://ng.jumia.is/cms/jumialogonew.png"/><meta property="og:locale" content="en_NG"/><meta name="title" content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport"/><meta name="robots" content="index,follow"/><meta name="description" content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! "/><meta property="og:type" content="website"/><meta property="og:title" content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport"/><meta property="og:site_name" content="Jumia Nigeria"/><meta property="og:description" content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! "/><meta property="og:url" content="https://www.jumia.com.ng/"/><meta name="twitter:card" content="summary"/><meta name="twitter:site" content="@JumiaNigeria"/><meta name="twitter:title" content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport"/><meta name="twitter:description" content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! "/><link rel="alternate" href="android-app://com.jumia.android/JUMIA/NG?utm_source=google&amp;utm_medium=organic&amp;adjust_tracker=j1hd8h&amp;adjust_campaign=GOOGLE_SEARCH&amp;adjust_adgroup=https%3A%2F%2Fwww.jumia.com.ng%2F"/><link rel="canonical" href="https://www.jumia.com.ng/"/><link rel="alternate" href="https://www.jumia.com.eg/" hreflang="en-eg"/><link rel="alternate" href="https://www.jumia.com.eg/ar/" hreflang="ar"/><link rel="alternate" href="https://www.jumia.ma/" hreflang="fr"/><link rel="alternate" href="https://www.jumia.ma/ar/" hreflang="ar-ma"/><link rel="alternate" href="https://www.jumia.com.dz/ar/" hreflang="ar-dz"/><link rel="alternate" href="https://www.jumia.co.ke/" hreflang="en-ke"/><link rel="alternate" href="https://www.jumia.ci/" hreflang="fr-ci"/><link rel="alternate" href="https://www.jumia.com.gh/" hreflang="en-gh"/><link rel="alternate" href="https://www.jumia.sn/" hreflang="fr-sn"/><link rel="alternate" href="https://www.jumia.com.dz/" hreflang="fr-dz"/><link rel="alternate" href="https://www.jumia.ug/" hreflang="en-ug"/><link rel="alternate" href="https://www.jumia.com.ng/" hreflang="en"/><meta property="fb:app_id" content="728795990650684"/><meta property="fb:pages" content="291297097615087"/><meta name="google-site-verification" content="4vr0StQ8YkyEzgDxkC_mgx0UMSH2xM3vkOaRpaMEjWM"/><meta name="google-site-verification" content="VeavdmtsHUH8fIEGpu4eeF-ryLp5ZXVUOmWmXWzV11I"/><meta name="msvalidate.01" content="66DCE7076C4C56245BAB83C687510491"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><meta name="application-name" content="Jumia"/><meta name="theme-color" content="#ffffff"/><link rel="manifest" crossorigin="use-credentials" href="https://www.jumia.com.ng/assets_he/manifest/jumia/ng.2bc74913.json"/><link rel="stylesheet" href="https://www.jumia.com.ng/assets_he/css/main.69e4030c.css"/><link rel="icon" type="image/ico" sizes="any" href="https://www.jumia.com.ng/assets_he/favicon.87f00114.ico"/><link rel="icon" type="image/svg+xml" href="https://www.jumia.com.ng/assets_he/favicon.adbd556a.svg"/><link rel="preconnect dns-prefetch" href="//bam.nr-data.net"/><link rel="preconnect dns-prefetch" href="//js-agent.newrelic.com"/><link rel="preconnect dns-prefetch" href="//www.google-analytics.com"/><link rel="preconnect dns-prefetch" href="//www.googletagmanager.com"/><link rel="preconnect dns-prefetch" href="//www.facebook.com"/><link rel="preconnect dns-prefetch" href="//connect.facebook.net"/><link rel="preconnect dns-prefetch" href="//static.criteo.net"/><link rel="preconnect dns-prefetch" href="//sslwidget.criteo.com"/><link rel="preconnect dns-prefetch" href="//dis.eu.criteo.com"/><link rel="preconnect dns-prefetch" href="//creativecdn.com"/><link rel="preconnect" href="https://ng.jumia.is"/><link href="//fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel="stylesheet"/></head><body><script type='text/javascript'>window.NREUM||(NREUM={});NREUM.info = {"agent":"","beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"b76de0635f","applicationID":"702890399","agentToken":null,"applicationTime":42.042305,"transactionName":"NVxXYhMHChFYVUELDQwWdkMSEgsPFn5aDwdCRRVmLjUw","queueTime":0,"ttGuid":"8d84a6cb82271c91"}; (window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},feature_flags:["soft_nav"],distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"718362032",accountID:"67325",trustKey:"1300143",xpid:"UgEEU1NADwMCXFhSBAgO",licenseKey:"b76de0635f",applicationID:"702890399",browserID:"718362032"};;/*! For license information please see nr-loader-spa-1.316.0.min.js.LICENSE.txt */

### Integrate Requests with BeautifulSoup

In [9]:
r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

print(soup)

<!DOCTYPE html>
<html dir="ltr" lang="en"><head><meta charset="utf-8"/><title>Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport</title><meta content="https://ng.jumia.is/cms/jumialogonew.png" property="og:image"/><meta content="en_NG" property="og:locale"/><meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" name="title"/><meta content="index,follow" name="robots"/><meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " name="description"/><meta content="website" property="og:type"/><meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" property="og:title"/><meta content="Jumia Nigeria" property="og:site_name"/><meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " property="og:description"/><meta content="https://www.jumia.com.ng/" property="og:url"/><meta content="summary" name="twitter:card"/><meta content="@JumiaNigeria" name="twitter:site"/><meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" name="twitter:title"/><meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " name="twitter:description"/><link href="android-app://com.jumia.android/JUMIA/NG?utm_source=google&amp;utm_medium=organic&amp;adjust_tracker=j1hd8h&amp;adjust_campaign=GOOGLE_SEARCH&amp;adjust_adgroup=https%3A%2F%2Fwww.jumia.com.ng%2F" rel="alternate"/><link href="https://www.jumia.com.ng/" rel="canonical"/><link href="https://www.jumia.com.eg/" hreflang="en-eg" rel="alternate"/><link href="https://www.jumia.com.eg/ar/" hreflang="ar" rel="alternate"/><link href="https://www.jumia.ma/" hreflang="fr" rel="alternate"/><link href="https://www.jumia.ma/ar/" hreflang="ar-ma" rel="alternate"/><link href="https://www.jumia.com.dz/ar/" hreflang="ar-dz" rel="alternate"/><link href="https://www.jumia.co.ke/" hreflang="en-ke" rel="alternate"/><link href="https://www.jumia.ci/" hreflang="fr-ci" rel="alternate"/><link href="https://www.jumia.com.gh/" hreflang="en-gh" rel="alternate"/><link href="https://www.jumia.sn/" hreflang="fr-sn" rel="alternate"/><link href="https://www.jumia.com.dz/" hreflang="fr-dz" rel="alternate"/><link href="https://www.jumia.ug/" hreflang="en-ug" rel="alternate"/><link href="https://www.jumia.com.ng/" hreflang="en" rel="alternate"/><meta content="728795990650684" property="fb:app_id"/><meta content="291297097615087" property="fb:pages"/><meta content="4vr0StQ8YkyEzgDxkC_mgx0UMSH2xM3vkOaRpaMEjWM" name="google-site-verification"/><meta content="VeavdmtsHUH8fIEGpu4eeF-ryLp5ZXVUOmWmXWzV11I" name="google-site-verification"/><meta content="66DCE7076C4C56245BAB83C687510491" name="msvalidate.01"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/><meta content="Jumia" name="application-name"/><meta content="#ffffff" name="theme-color"/><link crossorigin="use-credentials" href="https://www.jumia.com.ng/assets_he/manifest/jumia/ng.2bc74913.json" rel="manifest"/><link href="https://www.jumia.com.ng/assets_he/css/main.69e4030c.css" rel="stylesheet"/><link href="https://www.jumia.com.ng/assets_he/favicon.87f00114.ico" rel="icon" sizes="any" type="image/ico"/><link href="https://www.jumia.com.ng/assets_he/favicon.adbd556a.svg" rel="icon" type="image/svg+xml"/><link href="//bam.nr-data.net" rel="preconnect dns-prefetch"/><link href="//js-agent.newrelic.com" rel="preconnect dns-prefetch"/><link href="//www.google-analytics.com" rel="preconnect dns-prefetch"/><link href="//www.googletagmanager.com" rel="preconnect dns-prefetch"/><link href="//www.facebook.com" rel="preconnect dns-prefetch"/><link href="//connect.facebook.net" rel="preconnect dns-prefetch"/><link href="//static.criteo.net" rel="preconnect dns-prefetch"/><link href="//sslwidget.criteo.com" rel="preconnect dns-prefetch"/><link href="//dis.eu.criteo.com" rel="preconnect dns-prefetch"/><link href="//creativecdn.com" rel="preconnect dns-prefetch"/><link href="https://ng.jumia.is" rel="preconnect"/><link href="//fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel="stylesheet"/></head><body><script type="text/javascript">window.NREUM||(NREUM={});NREUM.info = {"agent":"","beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"b76de0635f","applicationID":"702890399","agentToken":null,"applicationTime":74.993335,"transactionName":"NVxXYhMHChFYVUELDQwWdkMSEgsPFn5aDwdCRRVmLjUw","queueTime":0,"ttGuid":"d2a64fe694996526"}; (window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},feature_flags:["soft_nav"],distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"718362032",accountID:"67325",trustKey:"1300143",xpid:"UgEEU1NADwMCXFhSBAgO",licenseKey:"b76de0635f",applicationID:"702890399",browserID:"718362032"};;/*! For license information please see nr-loader-spa-1.316.0.min.js.LICENSE.txt */

In [8]:
r = requests.get(url)

soup = BeautifulSoup(r.text, 'html.parser')

print(soup.prettify())

<!DOCTYPE html>
<html dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport
  </title>
  <meta content="https://ng.jumia.is/cms/jumialogonew.png" property="og:image"/>
  <meta content="en_NG" property="og:locale"/>
  <meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" name="title"/>
  <meta content="index,follow" name="robots"/>
  <meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " name="description"/>
  <meta content="website" property="og:type"/>
  <meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" property="og:title"/>
  <meta content="Jumia Nigeria" property="og:site_name"/>
  <meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " property="og:description"/>
  <meta content="https://www.jumia.com.ng/" property="og:url"/>
  <meta content="summary" name="twitter:card"/>
  <meta content="@JumiaNigeria" name="twitter:site"/>
  <meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" name="twitter:title"/>
  <meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " name="twitter:description"/>
  <link href="android-app://com.jumia.android/JUMIA/NG?utm_source=google&amp;utm_medium=organic&amp;adjust_tracker=j1hd8h&amp;adjust_campaign=GOOGLE_SEARCH&amp;adjust_adgroup=https%3A%2F%2Fwww.jumia.com.ng%2F" rel="alternate"/>
  <link href="https://www.jumia.com.ng/" rel="canonical"/>
  <link href="https://www.jumia.com.eg/" hreflang="en-eg" rel="alternate"/>
  <link href="https://www.jumia.com.eg/ar/" hreflang="ar" rel="alternate"/>
  <link href="https://www.jumia.ma/" hreflang="fr" rel="alternate"/>
  <link href="https://www.jumia.ma/ar/" hreflang="ar-ma" rel="alternate"/>
  <link href="https://www.jumia.com.dz/ar/" hreflang="ar-dz" rel="alternate"/>
  <link href="https://www.jumia.co.ke/" hreflang="en-ke" rel="alternate"/>
  <link href="https://www.jumia.ci/" hreflang="fr-ci" rel="alternate"/>
  <link href="https://www.jumia.com.gh/" hreflang="en-gh" rel="alternate"/>
  <link href="https://www.jumia.sn/" hreflang="fr-sn" rel="alternate"/>
  <link href="https://www.jumia.com.dz/" hreflang="fr-dz" rel="alternate"/>
  <link href="https://www.jumia.ug/" hreflang="en-ug" rel="alternate"/>
  <link href="https://www.jumia.com.ng/" hreflang="en" rel="alternate"/>
  <meta content="728795990650684" property="fb:app_id"/>
  <meta content="291297097615087" property="fb:pages"/>
  <meta content="4vr0StQ8YkyEzgDxkC_mgx0UMSH2xM3vkOaRpaMEjWM" name="google-site-verification"/>
  <meta content="VeavdmtsHUH8fIEGpu4eeF-ryLp5ZXVUOmWmXWzV11I" name="google-site-verification"/>
  <meta content="66DCE7076C4C56245BAB83C687510491" name="msvalidate.01"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Jumia" name="application-name"/>
  <meta content="#ffffff" name="theme-color"/>
  <link crossorigin="use-credentials" href="https://www.jumia.com.ng/assets_he/manifest/jumia/ng.2bc74913.json" rel="manifest"/>
  <link href="https://www.jumia.com.ng/assets_he/css/main.69e4030c.css" rel="stylesheet"/>
  <link href="https://www.jumia.com.ng/assets_he/favicon.87f00114.ico" rel="icon" sizes="any" type="image/ico"/>
  <link href="https://www.jumia.com.ng/assets_he/favicon.adbd556a.svg" rel="icon" type="image/svg+xml"/>
  <link href="//bam.nr-data.net" rel="preconnect dns-prefetch"/>
  <link href="//js-agent.newrelic.com" rel="preconnect dns-prefetch"/>
  <link href="//www.google-analytics.com" rel="preconnect dns-prefetch"/>
  <link href="//www.googletagmanager.com" rel="preconnect dns-prefetch"/>
  <link href="//www.facebook.com" rel="preconnect dns-prefetch"/>
  <link href="//connect.facebook.net" rel="preconnect dns-prefetch"/>
  <link href="//static.criteo.net" rel="preconnect dns-prefetch"/>
  <link href="//sslwidget.criteo.com" rel="preconnect dns-prefetch"/>
  <link href="//dis.eu.criteo.com" rel="preconnect dns-prefetch"/>
  <link href="//creativecdn.com" rel="preconnect dns-prefetch"/>
  <link href="https://ng.jumia.is" rel="preconnect"/>
  <link href="//fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel="stylesheet"/>
 </head>
 <body>
  <script type="text/javascript">
   window.NREUM||(NREUM={});NREUM.info = {"agent":"","beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"b76de0635f","applicationID":"702890399","agentToken":null,"applicationTime":43.260656,"transactionName":"NVxXYhMHChFYVUELDQwWdkMSEgsPFn5aDwdCRRVmLjUw","queueTime":0,"ttGuid":"2687200cfccd66fd"}; (window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},feature_flags:["soft_nav"],distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"718362032",accountID:"67325",trustKey:"1300143",xpid:"UgEEU1NADwMCXFhSBAgO",licenseKey:"b76de0635f",applicationID:"702890399",browserID:"718362032"};;/*! For license information please see nr-loader-spa-1.316.0.min.js.LICENSE.txt */

In [10]:
print(soup.head)

<head><meta charset="utf-8"/><title>Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport</title><meta content="https://ng.jumia.is/cms/jumialogonew.png" property="og:image"/><meta content="en_NG" property="og:locale"/><meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" name="title"/><meta content="index,follow" name="robots"/><meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " name="description"/><meta content="website" property="og:type"/><meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" property="og:title"/><meta content="Jumia Nigeria" property="og:site_name"/><meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " property="og:description"/><meta content="https://www.jumia.com.ng/" property="og:url"/><meta content="summary" name="twitter:card"/><meta content="@JumiaNigeria" name="twitter:site"/><meta content="Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport" name="twitter:title"/><meta content="Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! " name="twitter:description"/><link href="android-app://com.jumia.android/JUMIA/NG?utm_source=google&amp;utm_medium=organic&amp;adjust_tracker=j1hd8h&amp;adjust_campaign=GOOGLE_SEARCH&amp;adjust_adgroup=https%3A%2F%2Fwww.jumia.com.ng%2F" rel="alternate"/><link href="https://www.jumia.com.ng/" rel="canonical"/><link href="https://www.jumia.com.eg/" hreflang="en-eg" rel="alternate"/><link href="https://www.jumia.com.eg/ar/" hreflang="ar" rel="alternate"/><link href="https://www.jumia.ma/" hreflang="fr" rel="alternate"/><link href="https://www.jumia.ma/ar/" hreflang="ar-ma" rel="alternate"/><link href="https://www.jumia.com.dz/ar/" hreflang="ar-dz" rel="alternate"/><link href="https://www.jumia.co.ke/" hreflang="en-ke" rel="alternate"/><link href="https://www.jumia.ci/" hreflang="fr-ci" rel="alternate"/><link href="https://www.jumia.com.gh/" hreflang="en-gh" rel="alternate"/><link href="https://www.jumia.sn/" hreflang="fr-sn" rel="alternate"/><link href="https://www.jumia.com.dz/" hreflang="fr-dz" rel="alternate"/><link href="https://www.jumia.ug/" hreflang="en-ug" rel="alternate"/><link href="https://www.jumia.com.ng/" hreflang="en" rel="alternate"/><meta content="728795990650684" property="fb:app_id"/><meta content="291297097615087" property="fb:pages"/><meta content="4vr0StQ8YkyEzgDxkC_mgx0UMSH2xM3vkOaRpaMEjWM" name="google-site-verification"/><meta content="VeavdmtsHUH8fIEGpu4eeF-ryLp5ZXVUOmWmXWzV11I" name="google-site-verification"/><meta content="66DCE7076C4C56245BAB83C687510491" name="msvalidate.01"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/><meta content="Jumia" name="application-name"/><meta content="#ffffff" name="theme-color"/><link crossorigin="use-credentials" href="https://www.jumia.com.ng/assets_he/manifest/jumia/ng.2bc74913.json" rel="manifest"/><link href="https://www.jumia.com.ng/assets_he/css/main.69e4030c.css" rel="stylesheet"/><link href="https://www.jumia.com.ng/assets_he/favicon.87f00114.ico" rel="icon" sizes="any" type="image/ico"/><link href="https://www.jumia.com.ng/assets_he/favicon.adbd556a.svg" rel="icon" type="image/svg+xml"/><link href="//bam.nr-data.net" rel="preconnect dns-prefetch"/><link href="//js-agent.newrelic.com" rel="preconnect dns-prefetch"/><link href="//www.google-analytics.com" rel="preconnect dns-prefetch"/><link href="//www.googletagmanager.com" rel="preconnect dns-prefetch"/><link href="//www.facebook.com" rel="preconnect dns-prefetch"/><link href="//connect.facebook.net" rel="preconnect dns-prefetch"/><link href="//static.criteo.net" rel="preconnect dns-prefetch"/><link href="//sslwidget.criteo.com" rel="preconnect dns-prefetch"/><link href="//dis.eu.criteo.com" rel="preconnect dns-prefetch"/><link href="//creativecdn.com" rel="preconnect dns-prefetch"/><link href="https://ng.jumia.is" rel="preconnect"/><link href="//fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel="stylesheet"/></head>

In [11]:
print(soup.head.title)

<title>Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport</title>

In [13]:
print(soup.body.div)

<div id="jm"><div class="banner" data-bnrid="57" data-end="2026-12-31T23:59:00+01:00" style="background:#6AC1D4;"><div class="row _no-go -phm"><a class="col16 ar _1168-56" data-ga4-creative_name="https://ng.jumia.is/cms/0-6-anniversary/2026/TOP-STRIP-BF-updated-ezgif.com-optimize.gif" data-ga4-creative_slot="banner_top" data-ga4-promotion_id="home_default_DTB_JA26_" data-ga4-promotion_name="DTB_JA26_" data-track-onclick="eecPromo" data-track-onview="eecPromo" href="https://www.jumia.com.ng/mlp-anniversary-explosion-day/"><img alt="DTB_JA26_" class="_ni" data-lazy="true" data-src="https://ng.jumia.is/cms/0-6-anniversary/2026/TOP-STRIP-BF-updated-ezgif.com-optimize.gif" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></a></div></div><div class="vb row -i-ctr -j-ctr _head -bg-gy05"><div class="col3 -df -j-start"><a class="_link -df -i-ctr -or5 -m -fs12" href="/marketplace-vendor/" rel="noopener" target="_blank"><svg class="ic -f-or5 -maxs" height="16" viewbox="0 0 24 24" width="16"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-services" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-services"></use></svg>Sell on Jumia</a></div><div class="col10 -df -j-ctr -fs0"><span class="vent-link" href="" title="Jumia"><svg class="ic" height="24" viewbox="0 0 75 24" width="75"><use href="https://www.jumia.com.ng/assets_he/images/i-global.dca212ad.svg#venture-jumia" xlink:href="https://www.jumia.com.ng/assets_he/images/i-global.dca212ad.svg#venture-jumia"></use></svg></span><a class="vent-link" href="https://pay.jumia.com.ng/?utm_source=jumia&amp;utm_medium=mall&amp;utm_campaign=venturebar" rel="nofollow noopener" target="_blank" title="JumiaPay"><svg class="ic" height="24" viewbox="0 0 60 24" width="60"><use href="https://www.jumia.com.ng/assets_he/images/i-global.dca212ad.svg#venture-pay" xlink:href="https://www.jumia.com.ng/assets_he/images/i-global.dca212ad.svg#venture-pay"></use></svg></a><a class="vent-link" href="https://www.jumia.com.ng/sp-jumia-delivery/" rel="nofollow noopener" target="_blank" title="jumia delivery"><svg class="ic" height="24" viewbox="0 0 111 24" width="111"><use href="https://www.jumia.com.ng/assets_he/images/i-global.dca212ad.svg#venture-delivery" xlink:href="https://www.jumia.com.ng/assets_he/images/i-global.dca212ad.svg#venture-delivery"></use></svg></a></div><div class="col3 -df -j-end -wt -mla -gy5"></div></div><header class="header"><section class="row -i-ctr -fw-nw -pvm"><div class="col3 -df -i-ctr"><a class="-df -i-ctr -mra" href="/"><svg aria-label="Jumia Nigeria: Online Shopping for Electronics, Phones &amp; Fashion" class="ic" height="30" role="img" viewbox="0 0 172 30" width="134"><use href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#logo" xlink:href="https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg#logo"></use></svg></a></div><div class="cola find -df -pvm"><form action="/catalog/" class="-rad24 -paxs" data-track-onsubmit="search" data-track-providers="ga4|moengage" id="search" method="get" role="search"><svg class="ic -mlm" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#search" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#search"></use></svg><input aria-label="Search" autocomplete="off" id="fi-q" name="q" placeholder="Search products, brands and categories" required="" type="text" value=""/><button aria-label="Reset" class="rst" type="button"><svg class="ic" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#close" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#close"></use></svg></button><div class="sug"><div data-sec="suggestions"></div><div data-sec="recommendedsearches"></div><div data-sec="recentsearches"></div><div data-sec="topsearches"></div></div><button class="btn _prim _md _search -fsh0 -rad24" type="submit">Search</button></form></div><div class="col -df -j-bet -m -phn -i-ctr -pvm"><div class="dpdw _pcent" data-dpdw="true"><input aria-controls="dpdw-login-box" aria-haspopup="true" aria-label="Account" class="tgl" id="dpdw-login" type="checkbox"/><label class="trig -df -i-ctr -fs16" for="dpdw-login"><span class="-fsh0 -mrs"><svg class="ic" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#person" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#person"></use></svg></span><span class="-elli">Account</span><svg class="ic -fsh0 -mlm" height="18" viewbox="0 0 24 24" width="18"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#arrow-down" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#arrow-down"></use></svg></label><div aria-labelledby="dpdw-login" class="box -r" id="dpdw-login-box" role="menu"><div class="inbox"><div class="-paxl -hr-bb"><a class="btn _prim -fw _md" href="/customer/account/login/?return=%2F" rel="nofollow">Sign In</a></div><a class="-df -i-ctr -pam -hov-bg-gy05 -hov-m" href="/customer/account/index/" rel="nofollow"><svg class="ic -mrxl -fsh0" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#person" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#person"></use></svg>My Account</a><a class="-df -i-ctr -pam -hov-bg-gy05 -hov-m" href="/customer/order/index/" rel="nofollow"><svg class="ic -mrxl -fsh0" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#orders" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#orders"></use></svg>Orders</a><a class="-df -i-ctr -pam -hov-bg-gy05 -hov-m" href="/customer/wishlist/index/" rel="nofollow"><svg class="ic -mrm -fsh0" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#favorite-border" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#favorite-border"></use></svg>Wishlist</a></div></div></div><div class="dpdw _pcent" data-dpdw="true"><input aria-controls="dpdw-help-box" aria-haspopup="true" aria-label="Help" class="tgl" id="dpdw-help" type="checkbox"/><label class="trig -df -i-ctr -fs16" for="dpdw-help"><span class="-fsh0 -mrs"><svg class="ic" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#help-outline" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#help-outline"></use></svg></span><span class="-elli">Help</span><svg class="ic -fsh0 -mlm" height="18" viewbox="0 0 24 24" width="18"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#arrow-down" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#arrow-down"></use></svg></label><div aria-labelledby="dpdw-help" class="box -r" id="dpdw-help-box" role="menu"><div class="inbox"><a class="-df -i-ctr -phxl -pvl -hov-bg-gy05 -hov-m" href="https://www.jumia.com.ng/sp-help-center/">Help Center</a><a class="-df -i-ctr -phxl -pvl -hov-bg-gy05 -hov-m" href="https://www.jumia.com.ng/sp-help-center/?page=place+an+order">Place an order</a><a class="-df -i-ctr -phxl -pvl -hov-bg-gy05 -hov-m" href="https://www.jumia.com.ng/sp-help-center/?page=pay+for+your+order">Payment options</a><a class="-df -i-ctr -phxl -pvl -hov-bg-gy05 -hov-m" href="https://www.jumia.com.ng/sp-help-center/?page=track+your+order">Track an order</a><a class="-df -i-ctr -phxl -pvl -hov-bg-gy05 -hov-m" href="https://www.jumia.com.ng/sp-help-center/?page=cancel+an+order">Cancel an order</a><a class="-df -i-ctr -phxl -pvl -hov-bg-gy05 -hov-m" href="https://www.jumia.com.ng/sp-return-policy/">Returns &amp; Refunds</a><a class="-df -i-ctr -phxl -pvl -hov-bg-gy05 -hov-m" href="https://www.jumia.com.ng/consent-delete/">Cookie Preferences</a><div class="-hr -paxl"><div class="-tac _hx2 -fs0"><button class="btn _prim _md _i -fw" data-btn-lc="true" data-eventaction="open" data-eventcategory="LiveChat" data-eventname="live_chat_open" data-track-onclick="true"><svg class="ic" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#chat" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#chat"></use></svg><span>Live Chat</span></button></div><a aria-label="WhatsApp" class="btn _md _i _wpp -fw -mtm" data-eventaction="Open" data-eventcategory="WhatsApp" data-eventname="whatsapp_open" data-track-onclick="true" href="https://wa.me/2349139368685" rel="noopener" target="_blank"><svg class="ic -fw" height="24" viewbox="0 0 104 24" width="104"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#whatsapp" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#whatsapp"></use></svg></a></div></div></div></div><a class="-df -i-ctr -gy9 -hov-or5 -phm -fs16" href="/cart/"><span class="-mrs -fs0" id="ci"><svg class="ic" height="24" viewbox="0 0 24 24" width="24"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#shopping-cart" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#shopping-cart"></use></svg></span>Cart</a></div></section></header><main class="has-b2top"><style>@media(min-width:1200px){main{background:center 0 no-repeat url('https://ng.jumia.is/cms/0-6-anniversary/2026/Explosion-day/June-12/01-todayonly/BG_EXPLOSION-DAY.gif');}}main{background-color:#5AB0CD;}</style><div class="row -pvxl"><div class="col16 -df -j-bet -pbm"><div class="flyout-w -fsh0 -fs0"><div class="flyout" role="menu"><a class="itm" href="https://www.jumia.com.ng/mlp-official-stores/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-mall" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-mall"></use></svg><span class="text">Official Store</span></a><a class="itm" href="https://www.jumia.com.ng/mlp-appliances/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-kitchen-dinning" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-kitchen-dinning"></use></svg><span class="text">Appliances</span></a><a class="itm" href="/phones-tablets/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-mobile" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-mobile"></use></svg><span class="text">Phones &amp; Tablets</span></a><a class="itm" href="/health-beauty/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-beauty" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-beauty"></use></svg><span class="text">Health &amp; Beauty</span></a><a class="itm" href="/home-office/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-home" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-home"></use></svg><span class="text">Home &amp; Office</span></a><a class="itm" href="/electronics/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-tv" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-tv"></use></svg><span class="text">Electronics</span></a><a class="itm" href="/category-fashion-by-jumia/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-fashion" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-fashion"></use></svg><span class="text">Fashion</span></a><a class="itm" href="https://www.jumia.com.ng/groceries/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-groceries" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-groceries"></use></svg><span class="text">Supermarket</span></a><a class="itm" href="/computing/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-computing" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-computing"></use></svg><span class="text">Computing</span></a><a class="itm" href="/baby-products/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-baby" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-baby"></use></svg><span class="text">Baby Products</span></a><a class="itm" href="/video-games/" role="menuitem"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-games" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-games"></use></svg><span class="text">Gaming</span></a><span class="itm" role="menuitem" tabindex="0"><svg class="ic -mrxs -fsh0" height="20" viewbox="0 0 24 24" width="20"><use href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-othercategories" xlink:href="https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg#cat-othercategories"></use></svg><span class="text">Other categories</span></span></div></div><div class="sldr _img _main -rad4 -oh -fsh0 -mhxl" data-track-onsliderview="eecPromo" id="sl-topblock"><input checked="" class="sld" id="sl-topblock-sld-1" name="sl-topblock-sld" type="radio"/><a class="itm" data-ga4-creative_name="https://ng.jumia.is/cms/0-6-anniversary/2026/Explosion-day/June-12/01-todayonly/Artboard-1-ezgif.com-optimize.gif" data-ga4-creative_slot="slider_1_1" data-ga4-promotion_id="home_default_SX_JA26_HPAGE_4" data-ga4-promotion_name="SX_JA26_HPAGE_4" data-track-onclick="eecPromo" href="https://www.jumia.com.ng/mlp-anniversary-explosion-day/"><img alt="ANNIVERSARY DEA" class="-fw" data-lazy-slide="true" data-src="https://ng.jumia.is/cms/0-6-anniversary/2026/Explosion-day/June-12/01-todayonly/Artboard-1-ezgif.com-optimize.gif" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></a><label aria-label="Go to slide 8" class="lab" for="sl-topblock-sld-8"></label><label aria-label="Go to slide 1" class="dot" for="sl-topblock-sld-1"></label><input class="sld" id="sl-topblock-sld-2" name="sl-topblock-sld" type="radio"/><a class="itm" data-ga4-creative_name="https://ng.jumia.is/cms/0-6-anniversary/2026/Explosion-day/June-12/Mega-flash-sales/Today-only/712x384.png" data-ga4-creative_slot="slider_1_2" data-ga4-promotion_id="home_default_SX_FSL_HPAGE_2" data-ga4-promotion_name="SX_FSL_HPAGE_2" data-track-onclick="eecPromo" href="https://www.jumia.com.ng/flash-sales/"><img alt="FLASH SALES" class="-fw" data-lazy-slide="true" data-src="https://ng.jumia.is/cms/0-6-anniversary/2026/Explosion-day/June-12/Mega-flash-sales/Today-only/712x384.png" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></a><label aria-label="Go to slide 1" class="lab" for="sl-topblock-sld-1"></label><label aria-label="Go to slide 2" class="dot" for="sl-topblock-sld-2"></label><input class="sld" id="sl-topblock-sld-3" name="sl-topblock-sld" type="radio"/><a class="itm" data-ga4-creative_name="https://ng.jumia.is/cms/0-6-anniversary/2026/treasure-hunt/12-june/rework/712X384.gif" data-ga4-creative_slot="slider_1_3" data-ga4-promotion_id="home_default_SX_JA26_THUNT_HPAGE_3" data-ga4-promotion_name="SX_JA26_THUNT_HPAGE_3" data-track-onclick="eecPromo" href="https://www.jumia.com.ng/mlp-treasure-hunt/"><img alt="TREASURE HUNT" class="-fw" data-lazy-slide="true" data-src="https://ng.jumia.is/cms/0-6-anniversary/2026/treasure-hunt/12-june/rework/712X384.gif" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></a><label aria-label="Go to slide 2" class="lab" for="sl-topblock-sld-2"></label><label aria-label="Go to slide 3" class="dot" for="sl-topblock-sld-3"></label><input class="sld" id="sl-topblock-sld-4" name="sl-topblock-sld" type="radio"/><a class="itm" data-ga4-creative_name="https://ng.jumia.is/cms/0-6-anniversary/2026/0-1-Global/Redefine-space/712x384.jpg" data-ga4-creative_slot="slider_1_4" data-ga4-promotion_id="home_default_SX_JG_HPAGE_5" data-ga4-promotion_name="SX_JG_HPAGE_5" data-track-onclick="eecPromo" href="https://www.jumia.com.ng/mlp-redefine-your-space/"><img alt="REDEFINE SPCAE" class="-fw" data-lazy-slide="true" data-src="https://ng.jumia.is/cms/0-6-anniversary/2026/0-1-Global/Redefine-space/712x384.jpg" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></a><label aria-label="Go to slide 3" class="lab" for="sl-topblock-sld-3"></label><label aria-label="Go to slide 4" class="dot" for="sl-topblock-sld-4"></label><input class="sld" id="sl-topblock-sld-5" name="sl-topblock-sld" type="radio"/><a class="itm" data-ga4-creative_name="https://ng.jumia.is/cms/0-6-anniversary/2026/Television-deals/DesktopHomepageSlider_712x384.png" data-ga4-creative_slot="slider_1_5" data-ga4-promotion_id="home_default_SX_ADS_TVDEALS_HPAGE_4" data-ga4-promotion_name="SX_ADS_TVDEALS_HPAGE_4" data-track-onclick="eecPromo" href="https://www.jumia.com.ng/televisions/"><img alt="TV DEALS" class="-fw" data-lazy-slide="true" data-src="https://ng.jumia.is/cms/0-6-anniversary/2026/Television-deals/DesktopHomepageSlider_712x384.png" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></a><label aria-label="Go to slide 4" class="lab" for="sl-topblock-sld-4"></label><label aria-label="Go to slide 5" class="dot" for="sl-topblock-sld-5"></label><input class="sld" id="sl-topblock-sld-6" name="sl-topblock-sld" type="radio"/><a class="itm" data-ga4-creative_name="https://ng.jumia.is/cms/0-6-anniversary/2026/08-world-cup/712x384.jpg" data-ga4-creative_slot="slider_1_6" data-ga4-promotion_id="home_default_SX_FOOTBALL_FEVER_HPAGE_7" data-ga4-promotion_name="SX_FOOTBALL_FEVER_HPAGE_7" data-track-onclick="eecPromo" href="https://www.jumia.com.ng/mlp-football-fever/"><img alt="FOOTBALL FEVER" class="-fw" data-lazy-slide="true" data-src="https://ng.jumia.is/cms/0-6-anniversary/2026/08-world-cup/712x384.jpg" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'/%3E"/></a><label aria-label="Go to slide 5" class="lab" for="sl-topblock-sld-5"></label><label aria-label="Go to slide 6" class="dot" for="sl-topblock-sld-6"></label><input class="sld" id="sl-topblock-sld-7" name="sl-topblock-sld" type="radio"/><a class="itm" data-ga4-creative_name="https://ng.jumia.is/cms/0-1-weekly-cps/0-2025/Global-mini-Campaigns/0-2-Updated-generic/Artboard1.jpg" data-ga4-creative_slot="slider_1_7" data-ga4-promotion_id="home_default_SX_JA26_GLOBAL_HPAGE_8" data-ga4-promotion_name="SX_JA26_GLOBAL_HPAGE_8" data-track-onclick="eecPromo" href="https://www.jumia.com.ng/mlp-global-store/"><img alt="GLOBAL" class="-fw" data-lazy-slide="true" data-src="https://ng.jumia.is/cms/0-1-weekly-cps/0-2025/Global-mini-Campaigns/0-2-Updated-generic/Artboard1.jpg" src="data:image/svg+xml,%3Csvg 

## Attribute

In [16]:
tag = soup.body.div.article
print(tag.attrs)

{'class': ['prd', '_box', '_hvr']}

In [17]:
atb = tag.attrs

print(atb['class'])

['prd', '_box', '_hvr']

## Navigable Strings

In [18]:
tag = soup.head.title

print(tag.text)

Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty & Sport

## find() Functions

In [19]:
url = 'https://www.jumia.com.ng/samsung-49-odyssey-oled-g93sd-dqhd-240hz-gaming-monitor-419195086.html'

r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

print(soup.find('h1'))

<h1 class="-fs20 -ptm -pbxs">Samsung 49" Odyssey OLED G93SD DQHD, 240Hz Gaming Monitor</h1>

## find_all()

In [22]:
url = 'https://www.jumia.com.ng/catalog/?q=refrigerator'

r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

products = (soup.find_all('h3', class_='name'))

In [23]:
print(products)

[<h3 class="name">Skyrun 85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.</h3>, <h3 class="name">Aeon 70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty</h3>, <h3 class="name">Aeon 85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty</h3>, <h3 class="name">Nexus 50 Litres Bedside Refrigerator (NX-65) - Silver</h3>, <h3 class="name">Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.</h3>, <h3 class="name">Hisense 90 Litres Single Door Refrigerator (REF 093 DR) - Silver With One Year Warranty</h3>, <h3 class="name">Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Starry Night Black.</h3>, <h3 class="name">Hisense 150 Litres Single Door Fridge (RS20S / RR20S) - Silver With 1 Year Warranty</h3>, <h3 class="name">Royal 55Litres  Refrigerator Direct Cool Single Door (RREF55BF)</h3>, <h3 class="name">TEKNOCOOL 128-liter double-door refrigerator designed with a top freezer 100% copper compressor 70% energy-saving fast cooling +free gift inside </h3>, <h3 class="name">Haier Thermocool 95 Litres Double Door Fridge Silver (HRF-95BEX) - Silver  + 3 Years Warranty</h3>, <h3 class="name">Skyrun 138L Double Door Top Mount Fridge BCD-138HW</h3>, <h3 class="name">Skyrun 138 Litres Double Door Top Mount Fridge (BCD-145A) - Inox</h3>, <h3 class="name">Hisense 154L Double Door Refrigerator (REF 200 DR) - Silver</h3>, <h3 class="name">TEKNOCOOL 170-liter double-door refrigerator designed with a top freezer 100% copper compressor 70% energy-saving fast cooling +free gift inside(170L)</h3>, <h3 class="name">Skyrun 118L Double Door Top Mount Fridge (BCD-118HC) - Sliver</h3>, <h3 class="name">Skyrun 195 Litres Double Door Top Mount Fridge (BCD-195HS) - Silver</h3>, <h3 class="name">Hisense 121 Litres Single Door Refrigerator (REF121DR) - Silver With One Year Warranty</h3>, <h3 class="name">Skyrun 80 Litres Single Door Anti-rust Fridge (BCD-90J) - INOX.</h3>, <h3 class="name">4L Large Capacity Car Refrigerator Food Grade Liner Cooler Warmer Mini Fridge</h3>, <h3 class="name">Haier Thermocool 145 Litres Double Door Refrigerator (HRF-160BEX R6)- Silver  + 3 Years Warranty</h3>, <h3 class="name">Skyrun 85-Litres Single Door Fridge (BCD-90G)  - Silver</h3>, <h3 class="name">Skyrun 93 Litres Single Door Fridge (BCD-95A) - Silver.</h3>, <h3 class="name">Hisense 124L Double Door Refrigerator REF172DR</h3>, <h3 class="name">Haier Thermocool 93 Litres Single Door DCool Refrigerator (HR- 135BA R6) - Black</h3>, <h3 class="name">Skyrun 85 Litres Double Door Top Mount Fridge (BCD-108J) - Gold</h3>, <h3 class="name">R12 R410a R404a R407a R600a R22 A/c Refrigerant Bottle Opener Can Open Any Refrigerant Bottle Distribution Valve</h3>, <h3 class="name">Aeon Beverage Showcase Cooler 243L / 1 Year Warranty</h3>, <h3 class="name">TEKNOCOOL 200-litre  double door refrigerator 100% copper compressor 70% energy-saving fast cooling +free gift inside </h3>, <h3 class="name">Haier Thermocool 185 Litres Double Door Refrigerator (HRF-185BLUX) - Silver  + 2 Years Warranty</h3>, <h3 class="name">Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Black</h3>, <h3 class="name">Royal RREF105BF Refrigerator Direct Cool Single Door 105L</h3>, <h3 class="name">Skyrun 200L Double Door Top Mount Fridge (BCD-200K) -Grey</h3>, <h3 class="name">Mini Folding Compact Umbrella With Case</h3>, <h3 class="name">Skyrun 138-Litres Double Door Top Mount Fridge BCD-145A-Grey</h3>, <h3 class="name">Skyrun 450 Litres Side By Side No Frost Fridge (BCD-450W) - Gray</h3>, <h3 class="name">Skyrun 118L Double Door Top Mount Fridge (BCD-128J) - Silver</h3>, <h3 class="name">Skyrun 93-Litres Single Door Fridge BCD-95A</h3>, <h3 class="name">Skyrun 300 Litres Multi-door Fridge (BCD-330HC) - Dark Gray</h3>, <h3 class="name">Portable Electronic 7.5L Cooling And Warming Refrigerator Car Fridge</h3>]

In [24]:
for i in products:
    print(i.text)

Skyrun 85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.
Aeon 70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty
Aeon 85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty
Nexus 50 Litres Bedside Refrigerator (NX-65) - Silver
Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.
Hisense 90 Litres Single Door Refrigerator (REF 093 DR) - Silver With One Year Warranty
Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Starry Night Black.
Hisense 150 Litres Single Door Fridge (RS20S / RR20S) - Silver With 1 Year Warranty
Royal 55Litres  Refrigerator Direct Cool Single Door (RREF55BF)
TEKNOCOOL 128-liter double-door refrigerator designed with a top freezer 100% copper compressor 70% energy-saving fast cooling +free gift inside
Haier Thermocool 95 Litres Double Door Fridge Silver (HRF-95BEX) - Silver  + 3 Years Warranty
Skyrun 138L Double Door Top Mount Fridge BCD-138HW
Skyrun 138 Litres Double Door Top Mount Fridge (BCD-145A) - Inox
Hisense 154L Double Door Refrigerator (REF 200 DR) - Silver
TEKNOCOOL 170-liter double-door refrigerator designed with a top freezer 100% copper compressor 70% energy-saving fast cooling +free gift inside(170L)
Skyrun 118L Double Door Top Mount Fridge (BCD-118HC) - Sliver
Skyrun 195 Litres Double Door Top Mount Fridge (BCD-195HS) - Silver
Hisense 121 Litres Single Door Refrigerator (REF121DR) - Silver With One Year Warranty
Skyrun 80 Litres Single Door Anti-rust Fridge (BCD-90J) - INOX.
4L Large Capacity Car Refrigerator Food Grade Liner Cooler Warmer Mini Fridge
Haier Thermocool 145 Litres Double Door Refrigerator (HRF-160BEX R6)- Silver  + 3 Years Warranty
Skyrun 85-Litres Single Door Fridge (BCD-90G)  - Silver
Skyrun 93 Litres Single Door Fridge (BCD-95A) - Silver.
Hisense 124L Double Door Refrigerator REF172DR
Haier Thermocool 93 Litres Single Door DCool Refrigerator (HR- 135BA R6) - Black
Skyrun 85 Litres Double Door Top Mount Fridge (BCD-108J) - Gold
R12 R410a R404a R407a R600a R22 A/c Refrigerant Bottle Opener Can Open Any Refrigerant Bottle Distribution Valve
Aeon Beverage Showcase Cooler 243L / 1 Year Warranty
TEKNOCOOL 200-litre  double door refrigerator 100% copper compressor 70% energy-saving fast cooling +free gift inside
Haier Thermocool 185 Litres Double Door Refrigerator (HRF-185BLUX) - Silver  + 2 Years Warranty
Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Black
Royal RREF105BF Refrigerator Direct Cool Single Door 105L
Skyrun 200L Double Door Top Mount Fridge (BCD-200K) -Grey
Mini Folding Compact Umbrella With Case
Skyrun 138-Litres Double Door Top Mount Fridge BCD-145A-Grey
Skyrun 450 Litres Side By Side No Frost Fridge (BCD-450W) - Gray
Skyrun 118L Double Door Top Mount Fridge (BCD-128J) - Silver
Skyrun 93-Litres Single Door Fridge BCD-95A
Skyrun 300 Litres Multi-door Fridge (BCD-330HC) - Dark Gray
Portable Electronic 7.5L Cooling And Warming Refrigerator Car Fridge

In [25]:
len(products)

40

## find_all() with RegEx

In [26]:
url = 'https://www.jumia.com.ng/catalog/?q=refrigerator'

r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

In [30]:
data = soup.find_all(string=re.compile('Royal', re.IGNORECASE))

In [31]:
print(data)

['Royal', 'Royal', 'Royal 55Litres  Refrigerator Direct Cool Single Door (RREF55BF)', 'Royal RREF105BF Refrigerator Direct Cool Single Door 105L', '{"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","dateModified":"2026-06-05T16:22:08.000Z","mainEntity":{"@type":"ItemList","numberOfItems":10,"itemListElement":[{"@type":"ListItem","position":1,"item":{"@type":"Product","name":"85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.","url":"https://www.jumia.com.ng/skyrun-85-litres-double-door-top-mount-fridge-bcd-108j-silver.-400099255.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/55/2990004/1.jpg?8172","offers":{"@type":"Offer","price":"181425.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":2,"item":{"@type":"Product","name":"70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty","url":"https://www.jumia.com.ng/aeon-70l-double-door-fridge-art85gj-dark-grey-1-year-warranty-401319085.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/58/0913104/6.jpg?7448","offers":{"@type":"Offer","price":"148625.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":3,"item":{"@type":"Product","name":"85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty","url":"https://www.jumia.com.ng/aeon-85l-double-door-fridge-art108gj-dark-grey-1-year-warranty-401319086.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/68/0913104/1.jpg?8942","offers":{"@type":"Offer","price":"169655.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":4,"item":{"@type":"Product","name":"50 Litres Bedside Refrigerator (NX-65) - Silver","url":"https://www.jumia.com.ng/nexus-50-litres-bedside-refrigerator-nx-65-silver-110735586.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/68/5537011/1.jpg?8707","offers":{"@type":"Offer","price":"99499.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":5,"item":{"@type":"Product","name":"70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.","url":"https://www.jumia.com.ng/skyrun-70-litres-double-door-top-mount-fridge-bcd-85hc-silver.-370801445.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/54/4108073/1.jpg?8797","offers":{"@type":"Offer","price":"159900.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":6,"item":{"@type":"Product","name":"90 Litres Single Door Refrigerator (REF 093 DR) - Silver With One Year Warranty","url":"https://www.jumia.com.ng/hisense-90-litres-single-door-refrigerator-ref-093-dr-silver-with-one-year-warranty-128248428.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/82/4842821/1.jpg?6184","offers":{"@type":"Offer","price":"173500.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":7,"item":{"@type":"Product","name":"70 Litres Double Door Top Mount Fridge (BCD-85HC) - Starry Night Black.","url":"https://www.jumia.com.ng/skyrun-70-litres-double-door-top-mount-fridge-bcd-85hc-starry-night-black.-377757053.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/35/0757773/1.jpg?9956","offers":{"@type":"Offer","price":"159999.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":8,"item":{"@type":"Product","name":"150 Litres Single Door Fridge (RS20S / RR20S) - Silver With 1 Year Warranty","url":"https://www.jumia.com.ng/hisense-150-litres-single-door-fridge-rs20s-rr20s-silver-with-1-year-warranty-128248430.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/03/4842821/1.jpg?7383","offers":{"@type":"Offer","price":"269000.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":9,"item":{"@type":"Product","name":"55Litres  Refrigerator Direct Cool Single Door (RREF55BF)","url":"https://www.jumia.com.ng/royal-55litres-refrigerator-direct-cool-single-door-rref55bf-407678121.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/12/1876704/1.jpg?4698","offers":{"@type":"Offer","price":"160000.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":10,"item":{"@type":"Product","name":"128-liter double-door refrigerator designed with a top freezer 100% copper compressor 70% energy-saving fast cooling +free gift inside ","url":"https://www.jumia.com.ng/teknocool-128-liter-double-door-refrigerator-designed-with-a-top-freezer-100-copper-compressor-70-energy-saving-fast-cooling-free-gift-inside-419738157.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/75/1837914/1.jpg?3512","offers":{"@type":"Offer","price":"279909.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}}]}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.jumia.com.ng/","name":"Home"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.jumia.com.ng/all-products/","name":"All Products"}}]},{"@type":"Organization","@id":"#organization","name":"Jumia Nigeria","alternateName":["Jumia Nigeria","Jumia NG","jumia.com.ng"],"url":"https://www.jumia.com.ng","logo":"https://www.jumia.com.ng/assets_he/logo_jumia.svg","address":{"@type":"PostalAddress","streetAddress":"9 Canal View Layout, Ajao Estate, Lagos","addressCountry":"NG"},"contactPoint":[{"@type":"ContactPoint","telephone":"02018881106","contactType":"customer service"},{"@type":"ContactPoint","telephone":"07006000000","contactType":"customer service"},{"@type":"ContactPoint","telephone":"2349139368685","contactType":"WhatsApp"}]}]}', 'window.__STORE__={"view":"Catalog","activeLanguage":"en","countryCode":"NG","languages":{"en":{"text":"English","default":true}},"tracking":{"gtm":{"key":"GTM-KS6DC65"},"ga4":{"key":"G-SDKHD9CQ3C"},"moengage":{"dataCenter":"dc_2","appId":"8UETEU0UG1ZWZOD9HUUD2RFC"},"mirakl":{"url":"https://t.eu1.target2sell.mirakl.net/1.1/json/T/t","publisherId":"2YSVTHCK31PGHE","pageId":"2000","userId":"8fb7f846-669d-11f1-a189-82cbb5e059a8","view":{"productId":"SK821HA7J2MYGNAFAMZ|AE140HA7KQHIMNAFAMZ|AE140HA7QOTKENAFAMZ|NE493HA2SCOV9NAFAMZ|SK821HA5V094NNAFAMZ|HI368HA30N9RUNAFAMZ|SK821HA5JHU4HNAFAMZ|HI368HA1PM0ZENAFAMZ|RO953HA6TEM1INAFAMZ|TE766HA7UWU5RNAFAMZ|HA992HA0LULBUNAFAMZ|SK821HA0K255FNAFAMZ|SK821HA78EL3DNAFAMZ|HI368HA689IA7NAFAMZ|TE766HA84OCHBNAFAMZ|SK821HA5SWCNZNAFAMZ|SK821HA4HV40JNAFAMZ|HI368HA2CBITRNAFAMZ|SK821HA72G91LNAFAMZ|GE779HA738POINAFAMZ|HA992HA2UHEUFNAFAMZ|SK821HA4UGKCVNAFAMZ|SK821HA6WHWZTNAFAMZ|HI368HA1U14WBNAFAMZ|HA992HA89E6FINAFAMZ|SK821HA5E6038NAFAMZ|GE779HA6MSB9ZNAFAMZ|AE140HA7XVC17NAFAMZ|TE766HA7ONSB3NAFAMZ|HA992HA36E2XZNAFAMZ|SK821HA5EZJJ5NAFAMZ|RO953HA7DAA8NNAFAMZ|SK821HA3GGG8NNAFAMZ|GE779HA5YMYTFNAFAMZ|SK821HA0COO2WNAFAMZ|SK821HA5CUYIBNAFAMZ|SK821HA7G8T47NAFAMZ|SK821HA1BT8RSNAFAMZ|SK821HA6MOXFLNAFAMZ|GE779HA7O5X93NAFAMZ","pageNumber":"1","keywords":"refrigerator"}},"msClarity":{"key":"rgehulgxob"},"data":{"url":"/catalog/?q=refrigerator","abTests":"SearchABTest:defaultabtest#SponProdPdpV3:B","pageType":"catalog","pageSubtype":"searchResults","pageKey":"catalog_searchResults","pageTitle":"search-results","searchTerm":"refrigerator","isSecondChance":false}},"cookieConsent":{"advertising":false,"analytics":false,"personalization":false},"csrfToken":"ee89aa51f6cb40430069367930870a75","user":{"isGuest":true},"messages":[],"response":null,"cart":{"count":0},"shop":"jumia","abTests":{"SearchABTest":"defaultabtest","SponProdPdpV3":"B"},"url":"/catalog/?q=refrigerator","sprites":{"icons":"https://www.jumia.com.ng/assets_he/images/i-icons.90109997.svg","global":"https://www.jumia.com.ng/assets_he/images/i-global.dca212ad.svg","shop-jumia":"https://www.jumia.com.ng/assets_he/images/i-shop-jumia.0072ec91.svg"},"liveChat":{"loadingText":"Live Chat is loading...","botImg":"https://www.jumia.com.ng/assets_he/images/bot.5beef7d8.svg"},"htmlErrors":{"valueMissing":"Required field","typeMismatch":"Invalid Information","patternMismatch":"Invalid Information","rangeOverflow":".","rangeUnderflow":"form_html-errors_range_underflow","tooLong":"Text too long","tooShort":"Text too short"},"lastSearch":{"skus":["SK821HA7J2MYGNAFAMZ","AE140HA7KQHIMNAFAMZ","AE140HA7QOTKENAFAMZ","NE493HA2SCOV9NAFAMZ","SK821HA5V094NNAFAMZ","HI368HA30N9RUNAFAMZ","SK821HA5JHU4HNAFAMZ","HI368HA1PM0ZENAFAMZ","RO953HA6TEM1INAFAMZ","TE766HA7UWU5RNAFAMZ","HA992HA0LULBUNAFAMZ","SK821HA0K255FNAFAMZ","SK821HA78EL3DNAFAMZ","HI368HA689IA7NAFAMZ","TE766HA84OCHBNAFAMZ"],"url":"/catalog/?q=refrigerator","query":"refrigerator"},"addToCart":{"common":{"buyNowQtySelection":{"showQtySelector":true,"cartQtyIncreaseCTA":"increase cart quantity","cartQtyDecreaseCTA":"decrease cart quantity"}},"default":{"buyNowCTA":"Add to cart","buyNowQtySelection":{"showQtySelector":true,"cartQtyIncreaseCTA":"increase cart quantity","cartQtyDecreaseCTA":"decrease cart quantity"},"isXhr":true}},"popups":{"addToCart":{"data":{"buyNowCTA":"Add to cart","buyNowQtySelection":{"showQtySelector":true,"cartQtyIncreaseCTA":"increase cart quantity","cartQtyDecreaseCTA":"decrease cart quantity"},"unavailableText":"Currently unavailable","viewUrl":"/cart/","continueCTA":"Continue Shopping","viewCTA":"Go to Cart","popupTitle":"Please select a variation","closeCTA":"close popup"},"template":"AddToCart"},"filters":{"dynData":{"1":{"title":"Jumia Express","markup":"<div class=\\"markup\\">The BEST products, delivered faster. \\n<br/>\\n<br/>\\nNow PAY on DELIVERY, Cash or Bank Transfer Anywhere, Zero Wahala! </div>"}}},"consentPopup":{"data":{},"template":"Default","shouldOpen":true,"disableOverlayClose":true,"hideCloseBtn":true}},"products":[{"sku":"SK821HA7J2MYGNAFAMZ","name":"85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.","displayName":"Skyrun 85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.","brand":"Skyrun","isShopExpress":true,"categories":["Home & Office","Tools & Home Improvement","Appliances","Refrigerators"],"prices":{"rawPrice":"181425.00","price":"₦ 181,425","priceEuro":"115.50","taxEuro":"8.06","oldPrice":"₦ 198,880","oldPriceEuro":"126.61","discount":"9%","discountEuro":"11.11"},"tags":"CFS|JA|JA_17|JA_30|JMALL|TBOOST","rating":{"average":3.9,"totalRatings":203},"image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/55/2990004/1.jpg?8172","imageAlt":"Skyrun 85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.","isSponsored":false,"lastModified":1770371647,"tracking":{"name":"85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.","categoryKey":"appliances-fridges-freezers","brandKey":"skyrun","isSecondChance":false},"url":"/skyrun-85-litres-double-door-top-mount-fridge-bcd-108j-silver.-400099255.html","badges":{"main":{"name":"Official Store","identifier":"JMALL","url":"/all-products/?tag=JMALL"},"campaign":{"name":"Anniversary deal","identifier":"JA","url":"/all-products/?tag=JA","txtColor":"#002D3E","bgColor":"#6AC1D5"}},"isBuyable":true,"shopExpress":{"title":"Express Shipping"},"simples":[{"sku":"SK821HA7J2MYGNAFAMZ-698391112","loginUrl":"/customer/account/login/?tkWl=SK821HA7J2MYGNAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator","isBuyable":true,"name":"","prices":{"rawPrice":"181425.00","price":"₦ 181,425","priceEuro":"115.50","taxEuro":"8.06","oldPrice":"₦ 198,880","oldPriceEuro":"126.61","discount":"9%","discountEuro":"11.11"}}],"selectedVariation":"SK821HA7J2MYGNAFAMZ-698391112","wishlist":{"added":false,"removeUrl":"/wishlist/remove/SK821HA7J2MYGNAFAMZ/"},"loginUrl":"/customer/account/login/?tkWl=SK821HA7J2MYGNAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator"},{"sku":"AE140HA7KQHIMNAFAMZ","name":"70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty","displayName":"Aeon 70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty","brand":"Aeon","isShopExpress":true,"categories":["Home & Office","Tools & Home Improvement","Appliances","Refrigerators"],"prices":{"rawPrice":"148625.00","price":"₦ 148,625","priceEuro":"94.62","taxEuro":"6.60","oldPrice":"₦ 199,290","oldPriceEuro":"126.88","discount":"25%","discountEuro":"32.26"},"tags":"CFS|JA|JA_17|JA_30|JMALL|TBOOST","rating":{"average":3.8,"totalRatings":665},"image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/58/0913104/6.jpg?7448","imageAlt":"Aeon 70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty","isSponsored":false,"lastModified":1770734407,"tracking":{"name":"70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty","categoryKey":"appliances-fridges-freezers","brandKey":"aeon","isSecondChance":false},"url":"/aeon-70l-double-door-fridge-art85gj-dark-grey-1-year-warranty-401319085.html","badges":{"main":{"name":"Official Store","identifier":"JMALL","url":"/all-products/?tag=JMALL"},"campaign":{"name":"Anniversary deal","identifier":"JA","url":"/all-products/?tag=JA","txtColor":"#002D3E","bgColor":"#6AC1D5"}},"isBuyable":true,"shopExpress":{"title":"Express Shipping"},"simples":[{"sku":"AE140HA7KQHIMNAFAMZ-700372494","loginUrl":"/customer/account/login/?tkWl=AE140HA7KQHIMNAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator","isBuyable":true,"name":"","prices":{"rawPrice":"148625.00","price":"₦ 148,625","priceEuro":"94.62","taxEuro":"6.60","oldPrice":"₦ 199,290","oldPriceEuro":"126.88","discount":"25%","discountEuro":"32.26"}}],"selectedVariation":"AE140HA7KQHIMNAFAMZ-700372494","wishlist":{"added":false,"removeUrl":"/wishlist/remove/AE140HA7KQHIMNAFAMZ/"},"loginUrl":"/customer/account/login/?tkWl=AE140HA7KQHIMNAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator"},{"sku":"AE140HA7QOTKENAFAMZ","name":"85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty","displayName":"Aeon 85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty","brand":"Aeon","isShopExpress":true,"categories":["Home & Office","Tools & Home Improvement","Appliances","Refrigerators"],"prices":{"rawPrice":"169655.00","price":"₦ 169,655","priceEuro":"108.01","taxEuro":"7.54","oldPrice":"₦ 221,855","oldPriceEuro":"141.24","discount":"24%","discountEuro":"33.23"},"tags":"JA|JA_1|JA_17|JA_30|JMALL|TBOOST","rating":{"average":4.1,"totalRatings":347},"image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/68/0913104/1.jpg?8942","imageAlt":"Aeon 85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty","isSponsored":false,"lastModified":1770734459,"tracking":{"name":"85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty","categoryKey":"appliances-fridges-freezers","brandKey":"aeon","isSecondChance":false},"url":"/aeon-85l-double-door-fridge-art108gj-dark-grey-1-year-warranty-401319086.html","badges":{"main":{"name":"Official Store","identifier":"JMALL","url":"/all-products/?tag=JMALL"},"campaign":{"name":"Anniversary deal","identifier":"JA","url":"/all-products/?tag=JA","txtColor":"#002D3E","bgColor":"#6AC1D5"}},"isBuyable":true,"shopExpress":{"title":"Express Shipping"},"simples":[{"sku":"AE140HA7QOTKENAFAMZ-700372495","loginUrl":"/customer/account/login/?tkWl=AE140HA7QOTKENAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator","isBuyable":true,"name":"","prices":{"rawPrice":"169655.00","price":"₦ 169,655","priceEuro":"108.01","taxEuro":"7.54","oldPrice":"₦ 221,855","oldPriceEuro":"141.24","discount":"24%","discountEuro":"33.23"}}],"selectedVariation":"AE140HA7QOTKENAFAMZ-700372495","wishlist":{"added":false,"removeUrl":"/wishlist/remove/AE140HA7QOTKENAFAMZ/"},"loginUrl":"/customer/account/login/?tkWl=AE140HA7QOTKENAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator"},{"sku":"NE493HA2SCOV9NAFAMZ","name":"50 Litres Bedside Refrigerator (NX-65) - Silver","displayName":"Nexus 50 Litres Bedside Refrigerator (NX-65) - Silver","brand":"Nexus","isShopExpress":true,"categories":["Home & Office","Tools & Home Improvement","Appliances","Refrigerators"],"prices":{"rawPrice":"99499.00","price":"₦ 99,499","priceEuro":"63.34","taxEuro":"4.42","oldPrice":"₦ 130,000","oldPriceEuro":"82.76","discount":"24%","discountEuro":"19.42"},"tags":"JA|JA_30|JMALL|TBOOST","rating":{"average":3.9,"totalRatings":187},"image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/68/5537011/1.jpg?8707","imageAlt":"Nexus 50 Litres Bedside Refrigerator (NX-65) - Silver","isSponsored":false,"lastModified":1763568226,"tracking":{"name":"50 Litres Bedside Refrigerator (NX-65) - Silver","categoryKey":"appliances-fridges-freezers","brandKey":"nexus","isSecondChance":false},"url":"/nexus-50-litres-bedside-refrigerator-nx-65-silver-110735586.html","badges":{"main":{"name":"Official Store","identifier":"JMALL","url":"/all-products/?tag=JMALL"},"campaign":{"name":"Anniversary deal","identifier":"JA","url":"/all-products/?tag=JA","txtColor":"#002D3E","bgColor":"#6AC1D5"}},"isBuyable":true,"shopExpress":{"title":"Express Shipping"},"simples":[{"sku":"NE493HA2SCOV9NAFAMZ-152558832","loginUrl":"/customer/account/login/?tkWl=NE493HA2SCOV9NAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator","isBuyable":true,"name":"","prices":{"rawPrice":"99499.00","price":"₦ 99,499","priceEuro":"63.34","taxEuro":"4.42","oldPrice":"₦ 130,000","oldPriceEuro":"82.76","discount":"24%","discountEuro":"19.42"}}],"selectedVariation":"NE493HA2SCOV9NAFAMZ-152558832","wishlist":{"added":false,"removeUrl":"/wishlist/remove/NE493HA2SCOV9NAFAMZ/"},"loginUrl":"/customer/account/login/?tkWl=NE493HA2SCOV9NAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator"},{"sku":"SK821HA5V094NNAFAMZ","name":"70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.","displayName":"Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.","brand":"Skyrun","isShopExpress":true,"categories":["Home & Office","Tools & Home Improvement","Appliances","Refrigerators"],"prices":{"rawPrice":"159900.00","price":"₦ 159,900","priceEuro":"101.80","taxEuro":"7.10","oldPrice":"₦ 215,750","oldPriceEuro":"137.35","discount":"26%","discountEuro":"35.56"},"tags":"APWK|CFS|CP_1|CP_23|CP_MT119|CP_MT136|CP_MT73|CP_MT88|CP_MT9|CP_UN144|Camp_59|Camp_63|DOW_303|JA|JA_17|JA_30|JMALL|Merch_59|TBOOST|TW_11","rating":{"average":4,"totalRatings":195},"image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/54/4108073/1.jpg?8797","imageAlt":"Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.","isSponsored":false,"lastModified":1770371646,"tracking":{"name":"70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.","categoryKey":"appliances-fridges-freezers","brandKey":"skyrun","isSecondChance":false},"url":"/skyrun-70-litres-double-door-top-mount-fridge-bcd-85hc-silver.-370801445.html","badges":{"main":{"name":"Official Store","identifier":"JMALL","url":"/all-products/?tag=JMALL"},"campaign":{"name":"Anniversary deal","identifier":"JA","url":"/all-products/?tag=JA","txtColor":"#002D3E","bgColor":"#6AC1D5"}},"isBuyable":true,"shopExpress":{"title":"Express Shipping"},"simples":[{"sku":"SK821HA5V094NNAFAMZ-660209716","loginUrl":"/customer/account/login/?tkWl=SK821HA5V094NNAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator","isBuyable":true,"name":"","prices":{"rawPrice":"159900.00","price":"₦ 159,900","priceEuro":"101.80","taxEuro":"7.10","oldPrice":"₦ 215,750","oldPriceEuro":"137.35","discount":"26%","discountEuro":"35.56"}}],"selectedVariation":"SK821HA5V094NNAFAMZ-660209716","wishlist":{"added":false,"removeUrl":"/wishlist/remove/SK821HA5V094NNAFAMZ/"},"loginUrl":"/customer/account/login/?tkWl=SK821HA5V094NNAFAMZ&return=%2Fcatalog%2F%3Fq%3Drefrigerator"},{"sku":"HI368HA30N9RUNAFAMZ","name":"90 Litres Single Door Refrigerator (REF 093 DR) - Silver With One Year Warranty","displayName":"Hisense 90 Litres Single Door Refrigerator (REF 093 DR) - Silver With One Year Warranty","brand":"Hisense","isShopExpress":true,"categories":["Home & Office","Tool

In [32]:
for i in data:
    print(i)

Royal
Royal
Royal 55Litres  Refrigerator Direct Cool Single Door (RREF55BF)
Royal RREF105BF Refrigerator Direct Cool Single Door 105L
{"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","dateModified":"2026-06-05T16:22:08.000Z","mainEntity":{"@type":"ItemList","numberOfItems":10,"itemListElement":[{"@type":"ListItem","position":1,"item":{"@type":"Product","name":"85 Litres Double Door Top Mount Fridge (BCD-108J) - Silver.","url":"https://www.jumia.com.ng/skyrun-85-litres-double-door-top-mount-fridge-bcd-108j-silver.-400099255.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/55/2990004/1.jpg?8172","offers":{"@type":"Offer","price":"181425.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":2,"item":{"@type":"Product","name":"70L Double Door Fridge (ART85GJ) - Dark Grey + 1 Year Warranty","url":"https://www.jumia.com.ng/aeon-70l-double-door-fridge-art85gj-dark-grey-1-year-warranty-401319085.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/58/0913104/6.jpg?7448","offers":{"@type":"Offer","price":"148625.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":3,"item":{"@type":"Product","name":"85L Double Door Fridge (ART108GJ) - Dark Grey + 1 Year Warranty","url":"https://www.jumia.com.ng/aeon-85l-double-door-fridge-art108gj-dark-grey-1-year-warranty-401319086.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/68/0913104/1.jpg?8942","offers":{"@type":"Offer","price":"169655.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":4,"item":{"@type":"Product","name":"50 Litres Bedside Refrigerator (NX-65) - Silver","url":"https://www.jumia.com.ng/nexus-50-litres-bedside-refrigerator-nx-65-silver-110735586.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/68/5537011/1.jpg?8707","offers":{"@type":"Offer","price":"99499.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":5,"item":{"@type":"Product","name":"70 Litres Double Door Top Mount Fridge (BCD-85HC) - Silver.","url":"https://www.jumia.com.ng/skyrun-70-litres-double-door-top-mount-fridge-bcd-85hc-silver.-370801445.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/54/4108073/1.jpg?8797","offers":{"@type":"Offer","price":"159900.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":6,"item":{"@type":"Product","name":"90 Litres Single Door Refrigerator (REF 093 DR) - Silver With One Year Warranty","url":"https://www.jumia.com.ng/hisense-90-litres-single-door-refrigerator-ref-093-dr-silver-with-one-year-warranty-128248428.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/82/4842821/1.jpg?6184","offers":{"@type":"Offer","price":"173500.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":7,"item":{"@type":"Product","name":"70 Litres Double Door Top Mount Fridge (BCD-85HC) - Starry Night Black.","url":"https://www.jumia.com.ng/skyrun-70-litres-double-door-top-mount-fridge-bcd-85hc-starry-night-black.-377757053.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/35/0757773/1.jpg?9956","offers":{"@type":"Offer","price":"159999.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":8,"item":{"@type":"Product","name":"150 Litres Single Door Fridge (RS20S / RR20S) - Silver With 1 Year Warranty","url":"https://www.jumia.com.ng/hisense-150-litres-single-door-fridge-rs20s-rr20s-silver-with-1-year-warranty-128248430.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/03/4842821/1.jpg?7383","offers":{"@type":"Offer","price":"269000.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":9,"item":{"@type":"Product","name":"55Litres  Refrigerator Direct Cool Single Door (RREF55BF)","url":"https://www.jumia.com.ng/royal-55litres-refrigerator-direct-cool-single-door-rref55bf-407678121.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/12/1876704/1.jpg?4698","offers":{"@type":"Offer","price":"160000.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}},{"@type":"ListItem","position":10,"item":{"@type":"Product","name":"128-liter double-door refrigerator designed with a top freezer 100% copper compressor 70% energy-saving fast cooling +free gift inside ","url":"https://www.jumia.com.ng/teknocool-128-liter-double-door-refrigerator-designed-with-a-top-freezer-100-copper-compressor-70-energy-saving-fast-cooling-free-gift-inside-419738157.html","image":"https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/75/1837914/1.jpg?3512","offers":{"@type":"Offer","price":"279909.00","priceCurrency":"NGN","availability":"http://schema.org/InStock"}}}]}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.jumia.com.ng/","name":"Home"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.jumia.com.ng/all-products/","name":"All Products"}}]},{"@type":"Organization","@id":"#organization","name":"Jumia Nigeria","alternateName":["Jumia Nigeria","Jumia NG","jumia.com.ng"],"url":"https://www.jumia.com.ng","logo":"https://www.jumia.com.ng/assets_he/logo_jumia.svg","address":{"@type":"PostalAddress","streetAddress":"9 Canal View Layout, Ajao Estate, Lagos","addressCountry":"NG"},"contactPoint":[{"@type":"ContactPoint","telephone":"02018881106","contactType":"customer service"},{"@type":"ContactPoint","telephone":"07006000000","contactType":"customer service"},{"@type":"ContactPoint","telephone":"2349139368685","contactType":"WhatsApp"}]}]}

In [36]:
## Case Study: Web Scraping Jumia

url = 'https://www.jumia.com.ng/catalog/?q=laptops'

r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

In [39]:
# Product names
product_names = []
names = soup.find_all('h3', class_='name')
for name in names:
    product_names.append(name.string)

In [40]:
product_names

['Hp EliteBook 840 G6 Intel Core I5-8GB RAM-256GB SSD-Backlit Keyboard 11 Pro+BAG',
 'DELL  Latitude 7490 Intel Core I5- 8GB RAM/256GB SSD /BACKLIGHT KEYBOARD/WIN 11 PRO+BAG',
 "Asus Vivobook 15/ Intel Core i5-13420H/8GB RAM/512GB SSD/15.6' FHD/DOS/HD camera, With privacy shutter/Silver",
 'Hp EliteBook 645 G9 12th Gen- Ryzen 5 Pro 5675U/AMD 2.3 - 16GB RAM/256GB SSD WIN 11 PRO+BAG',
 'High Quality Padded Laptop Bag  Laptop Pouch Laptop Case Sleeve Messenger Office  Corporate Bag Seminar Souvenir Gift Item 15.6" ',
 "Asus V16 Creator Laptop/Intel Core i7-240H/16GB RAM/1TB SSD/NV RTX 5050 8GB/16' 144Hz/WIN11/Matte Black",
 'Asus Zenbook Duo Touch Screen /Intel Ultra 9-285H/32GB RAM/2TB SSD/14" 3K 120HZ/WIN11/Inkwell Grey',
 'DELL Latitude 7490 TOUCHSCREEN Core I7/16GB RAM 256 SSD/BACKLIGHT KEYBOARD/WIN 11PRO+BAG',
 'Power Plus Laptop Ultra Massive Power Bank (1300wh)',
 'Hp ProBook 11 X360-TOUCHSCREEN Intel Celeron 128GB SSD-4GB RAM WINDOWS10 Pro & Free USB Light',
 'Hp ELITEBOOK X360 1030 G2 TOUCHSCREEN CORE I5 8GB RAM/ 1TB SSD BACKLIT KEYBOARD FP READER WIN 11 PRO',
 'High Quality Padded Laptop Bag  Laptop Pouch Laptop Case Sleeve Messenger Office  Corporate Bag Seminar Souvenir Gift Item 15.6" ',
 'DELL Latitude 3190 INTEL CELERON 64GB SSD 4GB WINS 10 + Mouse & USB LIGHT',
 'Hp CHROMEBOOK 11 , INTEL CELERON, 4GB RAM,16GB EMMC + USB LIGHT ',
 'DELL  LATITUDE 3190, INTEL CELERON,4GB RAM/128GB SSD WINDOW 10 PRO +MOUSE',
 'Hp  EliteBook 840 G7 1Oth GEN TOUCHSCREEN Intel Core I5-16GB RAM/512GB SSD/Backlit Keyboard-WIN 11 Pro+ BAG',
 'High Quality Waterproof Backpack Laptop Bag  with Padded Laptop Sleeve Compartment School bag Student Office Corporate Business Backpack Seminar conference Bag Souvenir Gift Item ',
 'Hp EliteBook 840 G5 Intel Core I5-16GB RAM/1TB SSD/Win11+BAG',
 'Hp ProBook 11 X360-TOUCHSCREEN Intel Celeron 128GB SSD-4GB RAM WINDOWS11 Pro & USB Light',
 "Asus Vivobook 15 Intel Core i3-1215U/8GB RAM/512GB SSD/15.6' FHD/DOS/Silver-X1404VA",
 'DELL  LATITUDE 3190 2in1 X360 INTEL PENTIUM, 8GB RAM,128GB SSD TOUCHSCREEN WIN 10 +MOUSE & USB LIGHT',
 'Backpack 3 In 1 Multi Functional School Business Backpack',
 'Hp EliteBook 840 G5 TOUCHSCREEN Core I7-32GB RAM/512GB SSD/Backlit Keyboard/FP Reader WIN 11 Pro+BAG',
 'Hp Stream 11 Intel Celeron 4GB  RAM 64GB SSD Window 10 pro & USB Light ',
 'DELL  Latitude 3190 INTEL CELERON 64GB SSD 4GB WINDOW PRO 10 + Mouse',
 'Hp CHROMEBOOK 11 , INTEL CELERON, 4GB RAM,16GB EMMC + USB LIGHT ',
 'Hp EliteBook 840 G6 Intel Core I5-8GB RAM/256GB SSD/Backlit Keyboard/FP Reader Windows 11 Pro+BAG',
 'Premium Quality Padded Laptop Bag  Laptop Pouch Laptop Case Sleeve Messenger Office  Corporate Bag Seminar Souvenir Gift Item 15.6" Black ',
 'DELL Latitude 7490 Intel Core I7- 512GB SSD/16GB RAM BACKLIGHT KEYBOARD/WIN 11 PRO+BAG',
 'Hp EliteBook 840 G7 10th Gen Intel Core I5 Touchscreen 16GB RAM/256 SSD Win 11 Pro',
 'Hp EliteBook 840 G5 Intel Core I5-12GB RAM/512GB SSD/Backlit Keyboard/FP Reader Windows 11 Pro+BAG',
 'DELL LATITUDE 3190 2in1 X360 INTEL PENTIUM, 8GB RAM,128GB SSD TOUCHSCREEN WIN 10 +USB LIGHT & MOUSE',
 'DELL  LATITUDE 3190, INTEL CELERON,128GB SSD /4GB RAM/"11.0"SCREEN/WIN 11 PRO+MOUSE',
 'Hp  EliteBook 840 G6 TOUCHSCREEN Intel Core I5-16GB RAM/512GB SSD/ Backlit Keyboard/Windows11 Pro+BAG',
 'Hp  Chromebook 11A G8 Education Edition AMD A4-9120C 4GB DDR4-1866 SDRAM, 32GB eMMC 11.6-inch WLED HD Webcam Chrome OS',
 'Hp Stream 11 Intel Celeron 4GB RAM-64GB SSD WIN10+USB LIGHT',
 'Hp Stream 11 Pro G5 Touchscreen Intel Celeron 128GB SSD 4GB DDR4 RAM Windows 10 Pro + MOUSE & USB LIGHT FOR KEYBOARD',
 'DELL  Latitude 7490 Intel Core I7- 512GB SSD/16GB RAM BACKLIGHT KEYBOARD/WIN 11PRO+BAG',
 'Hp CHROMEBOOK 11 ,INTEL CELERON TOUCHSCREEN,4GB RAM,32GB EMMC WINS 10',
 "Asus Zenbook Duo Touch Screen /Intel Ultra 9-285H/32GB RAM/2TB SSD/14' 3K 120HZ/WIN11/Inkwell Gray-UX8406CA"]

In [ ]:
## Current Price

current_prices = []
prices = soup.find_all('div', class_='prc')
for price in prices:
    current_prices.append(price.string)

In [42]:
current_prices

['₦ 390,000',
 '₦ 350,000',
 '₦ 577,000',
 '₦ 500,000',
 '₦ 7,670 - ₦ 8,074',
 '₦ 1,400,000',
 '₦ 2,792,000',
 '₦ 525,000',
 '₦ 341,050',
 '₦ 190,000',
 '₦ 617,500',
 '₦ 8,074 - ₦ 67,924',
 '₦ 125,000',
 '₦ 99,500',
 '₦ 145,000',
 '₦ 550,000',
 '₦ 13,085',
 '₦ 560,450',
 '₦ 185,250',
 '₦ 463,900',
 '₦ 199,000',
 '₦ 10,290',
 '₦ 674,725',
 '₦ 145,000',
 '₦ 116,850',
 '₦ 99,500',
 '₦ 361,000',
 '₦ 12,499',
 '₦ 490,000',
 '₦ 480,000',
 '₦ 439,000',
 '₦ 197,999',
 '₦ 144,000',
 '₦ 510,000',
 '₦ 95,000',
 '₦ 130,000',
 '₦ 210,000',
 '₦ 520,000',
 '₦ 105,000',
 '₦ 2,792,000']

In [43]:
## Former Price

former_prices = []
prices = soup.find_all('div', class_='old')
for price in prices:
    former_prices.append(price.string)

In [44]:
former_prices

['₦ 750,000',
 '₦ 600,000',
 '₦ 674,585',
 '₦ 700,000',
 '₦ 13,000',
 '₦ 1,615,993',
 '₦ 3,077,418',
 '₦ 750,000',
 '₦ 515,000',
 '₦ 400,000',
 '₦ 9,000,000',
 '₦ 13,000 - ₦ 100,000',
 '₦ 850,000',
 '₦ 20,000',
 '₦ 750,000',
 '₦ 400,000',
 '₦ 498,601',
 '₦ 35,750',
 '₦ 950,000',
 '₦ 400,000',
 '₦ 180,000',
 '₦ 900,000',
 '₦ 20,000',
 '₦ 640,000',
 '₦ 890,000',
 '₦ 768,000',
 '₦ 150,000',
 '₦ 950,000',
 '₦ 3,077,453']

In [45]:
## discount percentage

discount_perc = []
discounts = soup.find_all('div', class_='bdg _dsct _sm')
for discount in discounts:
    discount_perc.append(discount.string)

In [46]:
discount_perc

['48%',
 '42%',
 '15%',
 '29%',
 '41%',
 '13%',
 '9%',
 '30%',
 '34%',
 '53%',
 '93%',
 '41%',
 '35%',
 '35%',
 '25%',
 '54%',
 '7%',
 '71%',
 '29%',
 '64%',
 '35%',
 '60%',
 '38%',
 '25%',
 '51%',
 '34%',
 '37%',
 '45%',
 '9%']

In [49]:
data = {
        'title': product_names, 
        'current_price': current_prices, 
        'former_prices': former_prices, 
        'discount': discount_perc
        }

laptops_df = pd.DataFrame.from_dict(data, orient='index').T

In [50]:
laptops_df

,title,current_price,former_prices,discount
0,Hp EliteBook 840 G6 Intel Core I5-8GB RAM-256G...,"₦ 390,000","₦ 750,000",48%
1,DELL Latitude 7490 Intel Core I5- 8GB RAM/256...,"₦ 350,000","₦ 600,000",42%
2,Asus Vivobook 15/ Intel Core i5-13420H/8GB RAM...,"₦ 577,000","₦ 674,585",15%
3,Hp EliteBook 645 G9 12th Gen- Ryzen 5 Pro 5675...,"₦ 500,000","₦ 700,000",29%
4,High Quality Padded Laptop Bag Laptop Pouch L...,"₦ 7,670 - ₦ 8,074","₦ 13,000",41%
5,Asus V16 Creator Laptop/Intel Core i7-240H/16G...,"₦ 1,400,000","₦ 1,615,993",13%
6,Asus Zenbook Duo Touch Screen /Intel Ultra 9-2...,"₦ 2,792,000","₦ 3,077,418",9%
7,DELL Latitude 7490 TOUCHSCREEN Core I7/16GB RA...,"₦ 525,000","₦ 750,000",30%
8,Power Plus Laptop Ultra Massive Power Bank (13...,"₦ 341,050","₦ 515,000",34%
9,Hp ProBook 11 X360-TOUCHSCREEN Intel Celeron 1...,"₦ 190,000","₦ 400,000",53%
10,Hp ELITEBOOK X360 1030 G2 TOUCHSCREEN CORE I5 ...,"₦ 617,500","₦ 9,000,000",93%
11,High Quality Padded Laptop Bag Laptop Pouch L...,"₦ 8,074 - ₦ 67,924","₦ 13,000 - ₦ 100,000",41%
12,DELL Latitude 3190 INTEL CELERON 64GB SSD 4GB ...,"₦ 125,000","₦ 850,000",35%
13,"Hp CHROMEBOOK 11 , INTEL CELERON, 4GB RAM,16GB...","₦ 99,500","₦ 20,000",35%
14,"DELL LATITUDE 3190, INTEL CELERON,4GB RAM/128...","₦ 145,000","₦ 750,000",25%
15,Hp EliteBook 840 G7 1Oth GEN TOUCHSCREEN Inte...,"₦ 550,000","₦ 400,000",54%
16,High Quality Waterproof Backpack Laptop Bag w...,"₦ 13,085","₦ 498,601",7%
17,Hp EliteBook 840 G5 Intel Core I5-16GB RAM/1TB...,"₦ 560,450","₦ 35,750",71%
18,Hp ProBook 11 X360-TOUCHSCREEN Intel Celeron 1...,"₦ 185,250","₦ 950,000",29%
19,Asus Vivobook 15 Intel Core i3-1215U/8GB RAM/5...,"₦ 463,900","₦ 400,000",64%
20,"DELL LATITUDE 3190 2in1 X360 INTEL PENTIUM, 8...","₦ 199,000","₦ 180,000",35%
21,Backpack 3 In 1 Multi Functional School Busine...,"₦ 10,290","₦ 900,000",60%
22,Hp EliteBook 840 G5 TOUCHSCREEN Core I7-32GB R...,"₦ 674,725","₦ 20,000",38%
23,Hp Stream 11 Intel Celeron 4GB RAM 64GB SSD W...,"₦ 145,000","₦ 640,000",25%
24,DELL Latitude 3190 INTEL CELERON 64GB SSD 4GB...,"₦ 116,850","₦ 890,000",51%
25,"Hp CHROMEBOOK 11 , INTEL CELERON, 4GB RAM,16GB...","₦ 99,500","₦ 768,000",34%
26,Hp EliteBook 840 G6 Intel Core I5-8GB RAM/256G...,"₦ 361,000","₦ 150,000",37%
27,Premium Quality Padded Laptop Bag Laptop Pouc...,"₦ 12,499","₦ 950,000",45%
28,DELL Latitude 7490 Intel Core I7- 512GB SSD/16...,"₦ 490,000","₦ 3,077,453",9%
29,Hp EliteBook 840 G7 10th Gen Intel Core I5 Tou...,"₦ 480,000",None,None
30,Hp EliteBook 840 G5 Intel Core I5-12GB RAM/512...,"₦ 439,000",None,None
31,"DELL LATITUDE 3190 2in1 X360 INTEL PENTIUM, 8G...","₦ 197,999",None,None
32,"DELL LATITUDE 3190, INTEL CELERON,128GB SSD /...","₦ 144,000",None,None
33,Hp EliteBook 840 G6 TOUCHSCREEN Intel Core I5...,"₦ 510,000",None,None
34,Hp Chromebook 11A G8 Education Edition AMD A4...,"₦ 95,000",None,None
35,Hp Stream 11 Intel Celeron 4GB RAM-64GB SSD WI...,"₦ 130,000",None,None
36,Hp Stream 11 Pro G5 Touchscreen Intel Celeron ...,"₦ 210,000",None,None
37,DELL Latitude 7490 Intel Core I7- 512GB SSD/1...,"₦ 520,000",None,None
38,"Hp CHROMEBOOK 11 ,INTEL CELERON TOUCHSCREEN,4G...","₦ 105,000",None,None
39,Asus Zenbook Duo Touch Screen /Intel Ultra 9-2...,"₦ 2,792,000",None,None

In [51]:
# for all the pages

pages = [x for x in range(1, 51)]
product_names = []
current_prices = []
former_prices = []
discount_perc = []

for page in pages:
    url = f'https://www.jumia.com.ng/catalog/?q=laptops&page={page}'
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'lxml')


    # Product names
    names = soup.find_all('h3', class_='name')
    for name in names:
        product_names.append(name.string)

    
    # Current Price    
    prices = soup.find_all('div', class_='prc')
    for price in prices:
        current_prices.append(price.string)

    # Former Price
    prices = soup.find_all('div', class_='old')
    for price in prices:
        former_prices.append(price.string)

        
    # Discount Percentage
    discounts = soup.find_all('div', class_='bdg _dsct _sm')
    for discount in discounts:
        discount_perc.append(discount.string)

In [53]:
data = {
        'title': product_names, 
        'current_price': current_prices, 
        'former_prices': former_prices, 
        'discount': discount_perc
        }

laptops_df = pd.DataFrame.from_dict(data, orient='index').T

laptops_df

,title,current_price,former_prices,discount
0,Hp EliteBook 840 G6 Intel Core I5-8GB RAM-256G...,"₦ 390,000","₦ 750,000",48%
1,Hp Probook x360 435 G8 Touch 11th Gen AMD RYZE...,"₦ 545,000","₦ 850,000",36%
2,Asus Vivobook 14 Flip 2in1 Touch Screen /Inte...,"₦ 1,406,000","₦ 1,607,706",13%
3,DELL Latitude 7490 Intel Core I5- 8GB RAM/256...,"₦ 350,000","₦ 600,000",42%
4,High Quality Padded Laptop Bag Laptop Pouch L...,"₦ 7,670 - ₦ 8,074","₦ 13,000",41%
...,...,...,...,...
1995,Hp ELITEBOOK x360 1030 G4 TOUCHSCREEN CORE I7 ...,"₦ 800,000",None,None
1996,Hp STREAM 11 INTEL CELERON 2GB RAM- 32GB HDD ...,"₦ 130,000",None,None
1997,DELL Latitude 5300 X360 TOUCHSCREEN Intel Core...,"₦ 420,000",None,None
1998,Hp Stream 11 - Intel Celeron- Education Editio...,"₦ 180,000",None,None
1999,DELL Latitude 7490 Intel Core I7/ 512GB SSD 16...,"₦ 550,000",None,None

## Data Transformation and Loading

In [57]:
laptops_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          2000 non-null   object
 1   current_price  2000 non-null   object
 2   former_prices  2000 non-null   object
 3   discount       2000 non-null   object
dtypes: object(4)
memory usage: 62.6+ KB

In [56]:
laptops_df.fillna({
    'former_prices': '0',
    'discount': '0%'
}, inplace=True)

In [58]:
from sqlalchemy import create_engine, text

engine = create_engine("postgresql://postgres:password@localhost:5432/postgres")

with engine.connect() as conn:
    conn.execution_options(isolation_level="AUTOCOMMIT").execute(
        text("CREATE DATABASE Zee_ecommerce")
    )

In [62]:
# define database connection parameters

db_params = {
    'host': 'localhost',
    'port': 5432,
    'database': 'zee_ecommerce',
    'username': 'postgres',
    'password': 'password'
}

# define the database connection url with db parameters
db_url = f"postgresql://{db_params['username']}:{db_params['password']}@{db_params['host']}:{db_params['port']}/{db_params['database']}"

# Create the database engine with the  db url
engine = create_engine(db_url)

#Connect to PostgreSQL server

with engine.connect() as connection:
    #create table and load the data into the table
    laptops_df.to_sql('laptops', connection, if_exists='replace', index=False)

print("Data loaded successfully into the laptops table in the Zee_ecommerce database.")

Data loaded successfully into the laptops table in the Zee_ecommerce database.